### ISSUE TITLE
制作了一张运行流程图

### ISSUE THREAD

**Issue by rickythink** [sl1673495/vue-reactive#1]
因为代码也不多, 我简单画了一张图，能否帮忙检查一下？

图比较大，需要等待一下

https://i.loli.net/2019/10/31/OYKnfFjJGrAVEak.png

**Comment by sl1673495** [comment]
嗯，看了下每个点的解读没啥问题，但是看这种图好像不太知道该怎么串起来形成一个完整的闭环。

**Comment by rickythink** [comment]
阿哈哈哈  我再研究一下

**Comment by rickythink** [comment]
哦对了，`this.dep!.notify()` 是什么意思。 有一个感叹号

**Comment by sl1673495** [comment]
> 哦对了，`this.dep!.notify()` 是什么意思。 有一个感叹号

这个是ts的语法，如果对ts不熟悉的话可以先看tag里的js-version。
